### ISSUE TITLE
The embedded command adds an extra space.

### ISSUE THREAD

**Issue by ushicow** [ksherlock/mpw-shell#5]
```
MPW Shell 0.4
# set X "`echo a`"
    echo a
  set X "a "
```

**Comment by ksherlock** [comment]
Carriage returns are converted to spaces in embedded commands.  In bash, all extra trailing spaces are stripped.  I'll verify that's what MPW does and update it.

https://github.com/ksherlock/mpw-shell/blob/9d4340b3ac06047071825e2869e3d289a4bd2211/mpw-shell-expand.rl#L160-L163

**Comment by ushicow** [comment]
[Fixed by commits on Nov 27, 2017 ](https://github.com/ksherlock/mpw-shell/commit/5d95f10dd8e3b3c55d0200348020c3f56787b3ab)
Thanks.
